version: "3.9"

networks:
  dev:
    driver: bridge

services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d:rw
    networks:
      - dev

  web:
    container_name: web
    hostname: web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ./src/web:/app
    ports:
      - 3000:5173
    depends_on:
      - api
    networks:
      - dev

  api:
    container_name: api
    hostname: api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./src/api:/app
    ports:
      - 3001:3001
    depends_on:
      - mysql
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_PASSWORD}
    networks:
      - dev
